### ISSUE TITLE
[GUI] Modify basic customer info

### ISSUE THREAD

**Issue by idontreallywolf** [EmirMulic/Projekt2_Newton#17]
A modal-window should popup where information on `selected customer` is displayed.
Both `first` & `lastname` should be modifiable and the changes made should be updated on both front- and backend.

**Comment by SiggeCinnamon** [comment]
No need for for a popup, but need a method for changing pNr, first and lastname is done.

**Comment by idontreallywolf** [comment]
@SiggeCinnamon alright, no popup. But only first & lastname can be changed.
> • ändra en kunds namn (personnummer ska inte kunna ändras)
